name: Generate ASCII artwork

on:
  push:
  workflow_dispatch:

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
      
    # Rest of your workflow steps